baseURL: https://cpl-uw.github.com
languageCode: en-us
defaultContentLanguage: en
title: Complex Play Lab
theme: cupper
googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
#enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Complex Play Lab
  homeMetaContent: Complex Play Lab
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  #codePenUser: someUser
  #katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Papers
      url: /paper/
      weight: 2
    - name: People
      url: /person/
      weight: 3
    - name: Apply
      url: /apply/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
